#pragma once


extern volatile struct limine_terminal_request terminal_request;
extern volatile struct limine_framebuffer_request framebuffer_request;
extern volatile struct limine_kernel_file_request kernel_request;
extern volatile struct limine_kernel_address_request address_request;