#pragma once

#define PORT_PIC_MASTER_CMD 0x20
#define PORT_PIC_MASTER_DATA 0x21

#define PORT_PIC_SLAVE_CMD 0xA0
#define PORT_PIC_SLAVE_DATA 0xA1

#define PORT_KBD_CMD 0x64
#define PORT_KBD_DATA 0x60